### ISSUE TITLE
Update-Mails kommen mehrfach

### ISSUE THREAD

**Issue by fsedarkalex** [easy-wi/easy-wi#17]
C&P aus Gitter:
Die Update-Mail kommt übrigens zum einen täglich (was nervt aber akzeptabel ist) und dann auhc immer gleich drei mal (was übetrieben ist)

**Comment by ulrichblock** [comment]
Update Mails von was genau? Game Server? Panel? Voice Server? Alle?

**Comment by fsedarkalex** [comment]
Vom Panel

**Comment by ulrichblock** [comment]
Dieses Repo war der Versuch ein Rewrite zu machen. Denke das wird nichts mehr, weil die Leute abgesprungen sind. Zu dem Thema gibt es bereits ein Issue im laufenden Repo: https://github.com/easy-wi/developer/issues/1032
